[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
atomic = true
combine_as_imports = true
include_trailing_comma = true
indent = 4
line_length = 88
lines_after_imports = 2
multi_line_output = 3
